[package]
name = "admintui"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3.4.1"
chrono = "0.4.39"
chrono-tz = "0.10.1"
cron-descriptor = "=0.1.0"
cron-parser = "0.10.0"
ratatui = "0.29.0"
regex = "1.11.1"
tui-textarea = "0.7.0"
unicode-width = "0.2.0"
